package com.test.entity;

public class Course {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.id
     *
     * @mbg.generated Wed Jan 18 20:11:21 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.uid
     *
     * @mbg.generated Wed Jan 18 20:11:21 CST 2017
     */
    private Integer uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.title
     *
     * @mbg.generated Wed Jan 18 20:11:21 CST 2017
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.summary
     *
     * @mbg.generated Wed Jan 18 20:11:21 CST 2017
     */
    private String summary;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.video_status
     *
     * @mbg.generated Wed Jan 18 20:11:21 CST 2017
     */
    private Integer videoStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.video_url
     *
     * @mbg.generated Wed Jan 18 20:11:21 CST 2017
     */
    private String videoUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.review_price
     *
     * @mbg.generated Wed Jan 18 20:11:21 CST 2017
     */
    private Integer reviewPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.type
     *
     * @mbg.generated Wed Jan 18 20:11:21 CST 2017
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.reserve_price
     *
     * @mbg.generated Wed Jan 18 20:11:21 CST 2017
     */
    private Integer reservePrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.status
     *
     * @mbg.generated Wed Jan 18 20:11:21 CST 2017
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.creat_time
     *
     * @mbg.generated Wed Jan 18 20:11:21 CST 2017
     */
    private Integer creatTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.course_time
     *
     * @mbg.generated Wed Jan 18 20:11:21 CST 2017
     */
    private Integer courseTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.reserve_num
     *
     * @mbg.generated Wed Jan 18 20:11:21 CST 2017
     */
    private Integer reserveNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.reserve_maxnum
     *
     * @mbg.generated Wed Jan 18 20:11:21 CST 2017
     */
    private Integer reserveMaxnum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.live_time
     *
     * @mbg.generated Wed Jan 18 20:11:21 CST 2017
     */
    private Integer liveTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.live_id
     *
     * @mbg.generated Wed Jan 18 20:11:21 CST 2017
     */
    private String liveId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.uv
     *
     * @mbg.generated Wed Jan 18 20:11:21 CST 2017
     */
    private String uv;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.vv
     *
     * @mbg.generated Wed Jan 18 20:11:21 CST 2017
     */
    private String vv;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.img_url
     *
     * @mbg.generated Wed Jan 18 20:11:21 CST 2017
     */
    private String imgUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.direct_id
     *
     * @mbg.generated Wed Jan 18 20:11:21 CST 2017
     */
    private Integer directId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.expert_url
     *
     * @mbg.generated Wed Jan 18 20:11:21 CST 2017
     */
    private String expertUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.update_time
     *
     * @mbg.generated Wed Jan 18 20:11:21 CST 2017
     */
    private Integer updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.course_type
     *
     * @mbg.generated Wed Jan 18 20:11:21 CST 2017
     */
    private Integer courseType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.series_type
     *
     * @mbg.generated Wed Jan 18 20:11:21 CST 2017
     */
    private Integer seriesType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.parent_id
     *
     * @mbg.generated Wed Jan 18 20:11:21 CST 2017
     */
    private Integer parentId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.id
     *
     * @return the value of course.id
     *
     * @mbg.generated Wed Jan 18 20:11:21 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.id
     *
     * @param id the value for course.id
     *
     * @mbg.generated Wed Jan 18 20:11:21 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.uid
     *
     * @return the value of course.uid
     *
     * @mbg.generated Wed Jan 18 20:11:21 CST 2017
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.uid
     *
     * @param uid the value for course.uid
     *
     * @mbg.generated Wed Jan 18 20:11:21 CST 2017
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.title
     *
     * @return the value of course.title
     *
     * @mbg.generated Wed Jan 18 20:11:21 CST 2017
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.title
     *
     * @param title the value for course.title
     *
     * @mbg.generated Wed Jan 18 20:11:21 CST 2017
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.summary
     *
     * @return the value of course.summary
     *
     * @mbg.generated Wed Jan 18 20:11:21 CST 2017
     */
    public String getSummary() {
        return summary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.summary
     *
     * @param summary the value for course.summary
     *
     * @mbg.generated Wed Jan 18 20:11:21 CST 2017
     */
    public void setSummary(String summary) {
        this.summary = summary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.video_status
     *
     * @return the value of course.video_status
     *
     * @mbg.generated Wed Jan 18 20:11:21 CST 2017
     */
    public Integer getVideoStatus() {
        return videoStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.video_status
     *
     * @param videoStatus the value for course.video_status
     *
     * @mbg.generated Wed Jan 18 20:11:21 CST 2017
     */
    public void setVideoStatus(Integer videoStatus) {
        this.videoStatus = videoStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.video_url
     *
     * @return the value of course.video_url
     *
     * @mbg.generated Wed Jan 18 20:11:21 CST 2017
     */
    public String getVideoUrl() {
        return videoUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.video_url
     *
     * @param videoUrl the value for course.video_url
     *
     * @mbg.generated Wed Jan 18 20:11:21 CST 2017
     */
    public void setVideoUrl(String videoUrl) {
        this.videoUrl = videoUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.review_price
     *
     * @return the value of course.review_price
     *
     * @mbg.generated Wed Jan 18 20:11:21 CST 2017
     */
    public Integer getReviewPrice() {
        return reviewPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.review_price
     *
     * @param reviewPrice the value for course.review_price
     *
     * @mbg.generated Wed Jan 18 20:11:21 CST 2017
     */
    public void setReviewPrice(Integer reviewPrice) {
        this.reviewPrice = reviewPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.type
     *
     * @return the value of course.type
     *
     * @mbg.generated Wed Jan 18 20:11:21 CST 2017
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.type
     *
     * @param type the value for course.type
     *
     * @mbg.generated Wed Jan 18 20:11:21 CST 2017
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.reserve_price
     *
     * @return the value of course.reserve_price
     *
     * @mbg.generated Wed Jan 18 20:11:21 CST 2017
     */
    public Integer getReservePrice() {
        return reservePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.reserve_price
     *
     * @param reservePrice the value for course.reserve_price
     *
     * @mbg.generated Wed Jan 18 20:11:21 CST 2017
     */
    public void setReservePrice(Integer reservePrice) {
        this.reservePrice = reservePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.status
     *
     * @return the value of course.status
     *
     * @mbg.generated Wed Jan 18 20:11:21 CST 2017
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.status
     *
     * @param status the value for course.status
     *
     * @mbg.generated Wed Jan 18 20:11:21 CST 2017
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.creat_time
     *
     * @return the value of course.creat_time
     *
     * @mbg.generated Wed Jan 18 20:11:21 CST 2017
     */
    public Integer getCreatTime() {
        return creatTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.creat_time
     *
     * @param creatTime the value for course.creat_time
     *
     * @mbg.generated Wed Jan 18 20:11:21 CST 2017
     */
    public void setCreatTime(Integer creatTime) {
        this.creatTime = creatTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.course_time
     *
     * @return the value of course.course_time
     *
     * @mbg.generated Wed Jan 18 20:11:21 CST 2017
     */
    public Integer getCourseTime() {
        return courseTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.course_time
     *
     * @param courseTime the value for course.course_time
     *
     * @mbg.generated Wed Jan 18 20:11:21 CST 2017
     */
    public void setCourseTime(Integer courseTime) {
        this.courseTime = courseTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.reserve_num
     *
     * @return the value of course.reserve_num
     *
     * @mbg.generated Wed Jan 18 20:11:21 CST 2017
     */
    public Integer getReserveNum() {
        return reserveNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.reserve_num
     *
     * @param reserveNum the value for course.reserve_num
     *
     * @mbg.generated Wed Jan 18 20:11:21 CST 2017
     */
    public void setReserveNum(Integer reserveNum) {
        this.reserveNum = reserveNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.reserve_maxnum
     *
     * @return the value of course.reserve_maxnum
     *
     * @mbg.generated Wed Jan 18 20:11:21 CST 2017
     */
    public Integer getReserveMaxnum() {
        return reserveMaxnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.reserve_maxnum
     *
     * @param reserveMaxnum the value for course.reserve_maxnum
     *
     * @mbg.generated Wed Jan 18 20:11:21 CST 2017
     */
    public void setReserveMaxnum(Integer reserveMaxnum) {
        this.reserveMaxnum = reserveMaxnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.live_time
     *
     * @return the value of course.live_time
     *
     * @mbg.generated Wed Jan 18 20:11:21 CST 2017
     */
    public Integer getLiveTime() {
        return liveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.live_time
     *
     * @param liveTime the value for course.live_time
     *
     * @mbg.generated Wed Jan 18 20:11:21 CST 2017
     */
    public void setLiveTime(Integer liveTime) {
        this.liveTime = liveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.live_id
     *
     * @return the value of course.live_id
     *
     * @mbg.generated Wed Jan 18 20:11:21 CST 2017
     */
    public String getLiveId() {
        return liveId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.live_id
     *
     * @param liveId the value for course.live_id
     *
     * @mbg.generated Wed Jan 18 20:11:21 CST 2017
     */
    public void setLiveId(String liveId) {
        this.liveId = liveId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.uv
     *
     * @return the value of course.uv
     *
     * @mbg.generated Wed Jan 18 20:11:21 CST 2017
     */
    public String getUv() {
        return uv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.uv
     *
     * @param uv the value for course.uv
     *
     * @mbg.generated Wed Jan 18 20:11:21 CST 2017
     */
    public void setUv(String uv) {
        this.uv = uv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.vv
     *
     * @return the value of course.vv
     *
     * @mbg.generated Wed Jan 18 20:11:21 CST 2017
     */
    public String getVv() {
        return vv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.vv
     *
     * @param vv the value for course.vv
     *
     * @mbg.generated Wed Jan 18 20:11:21 CST 2017
     */
    public void setVv(String vv) {
        this.vv = vv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.img_url
     *
     * @return the value of course.img_url
     *
     * @mbg.generated Wed Jan 18 20:11:21 CST 2017
     */
    public String getImgUrl() {
        return imgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.img_url
     *
     * @param imgUrl the value for course.img_url
     *
     * @mbg.generated Wed Jan 18 20:11:21 CST 2017
     */
    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.direct_id
     *
     * @return the value of course.direct_id
     *
     * @mbg.generated Wed Jan 18 20:11:21 CST 2017
     */
    public Integer getDirectId() {
        return directId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.direct_id
     *
     * @param directId the value for course.direct_id
     *
     * @mbg.generated Wed Jan 18 20:11:21 CST 2017
     */
    public void setDirectId(Integer directId) {
        this.directId = directId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.expert_url
     *
     * @return the value of course.expert_url
     *
     * @mbg.generated Wed Jan 18 20:11:21 CST 2017
     */
    public String getExpertUrl() {
        return expertUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.expert_url
     *
     * @param expertUrl the value for course.expert_url
     *
     * @mbg.generated Wed Jan 18 20:11:21 CST 2017
     */
    public void setExpertUrl(String expertUrl) {
        this.expertUrl = expertUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.update_time
     *
     * @return the value of course.update_time
     *
     * @mbg.generated Wed Jan 18 20:11:21 CST 2017
     */
    public Integer getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.update_time
     *
     * @param updateTime the value for course.update_time
     *
     * @mbg.generated Wed Jan 18 20:11:21 CST 2017
     */
    public void setUpdateTime(Integer updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.course_type
     *
     * @return the value of course.course_type
     *
     * @mbg.generated Wed Jan 18 20:11:21 CST 2017
     */
    public Integer getCourseType() {
        return courseType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.course_type
     *
     * @param courseType the value for course.course_type
     *
     * @mbg.generated Wed Jan 18 20:11:21 CST 2017
     */
    public void setCourseType(Integer courseType) {
        this.courseType = courseType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.series_type
     *
     * @return the value of course.series_type
     *
     * @mbg.generated Wed Jan 18 20:11:21 CST 2017
     */
    public Integer getSeriesType() {
        return seriesType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.series_type
     *
     * @param seriesType the value for course.series_type
     *
     * @mbg.generated Wed Jan 18 20:11:21 CST 2017
     */
    public void setSeriesType(Integer seriesType) {
        this.seriesType = seriesType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.parent_id
     *
     * @return the value of course.parent_id
     *
     * @mbg.generated Wed Jan 18 20:11:21 CST 2017
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.parent_id
     *
     * @param parentId the value for course.parent_id
     *
     * @mbg.generated Wed Jan 18 20:11:21 CST 2017
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }
}