package com.test.entity;

public class User {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.id
	 * @mbg.generated  Fri Jan 20 10:10:53 CST 2017
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.uid
	 * @mbg.generated  Fri Jan 20 10:10:53 CST 2017
	 */
	private Integer uid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.direct_url
	 * @mbg.generated  Fri Jan 20 10:10:53 CST 2017
	 */
	private String directUrl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.direct_pwd
	 * @mbg.generated  Fri Jan 20 10:10:53 CST 2017
	 */
	private String directPwd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.name
	 * @mbg.generated  Fri Jan 20 10:10:53 CST 2017
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.sumary
	 * @mbg.generated  Fri Jan 20 10:10:53 CST 2017
	 */
	private String sumary;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.title
	 * @mbg.generated  Fri Jan 20 10:10:53 CST 2017
	 */
	private String title;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.pice
	 * @mbg.generated  Fri Jan 20 10:10:53 CST 2017
	 */
	private Integer pice;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.type
	 * @mbg.generated  Fri Jan 20 10:10:53 CST 2017
	 */
	private Integer type;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.status
	 * @mbg.generated  Fri Jan 20 10:10:53 CST 2017
	 */
	private Integer status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.update_time
	 * @mbg.generated  Fri Jan 20 10:10:53 CST 2017
	 */
	private Integer updateTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.create_time
	 * @mbg.generated  Fri Jan 20 10:10:53 CST 2017
	 */
	private Integer createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.open_id
	 * @mbg.generated  Fri Jan 20 10:10:53 CST 2017
	 */
	private String openId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.subscribe
	 * @mbg.generated  Fri Jan 20 10:10:53 CST 2017
	 */
	private Integer subscribe;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.head_image_url
	 * @mbg.generated  Fri Jan 20 10:10:53 CST 2017
	 */
	private String headImageUrl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.nickname
	 * @mbg.generated  Fri Jan 20 10:10:53 CST 2017
	 */
	private String nickname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.sex
	 * @mbg.generated  Fri Jan 20 10:10:53 CST 2017
	 */
	private Integer sex;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.unionid
	 * @mbg.generated  Fri Jan 20 10:10:53 CST 2017
	 */
	private String unionid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.email
	 * @mbg.generated  Fri Jan 20 10:10:53 CST 2017
	 */
	private String email;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.mobile
	 * @mbg.generated  Fri Jan 20 10:10:53 CST 2017
	 */
	private String mobile;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.remarks
	 * @mbg.generated  Fri Jan 20 10:10:53 CST 2017
	 */
	private String remarks;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.id
	 * @return  the value of user.id
	 * @mbg.generated  Fri Jan 20 10:10:53 CST 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.id
	 * @param id  the value for user.id
	 * @mbg.generated  Fri Jan 20 10:10:53 CST 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.uid
	 * @return  the value of user.uid
	 * @mbg.generated  Fri Jan 20 10:10:53 CST 2017
	 */
	public Integer getUid() {
		return uid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.uid
	 * @param uid  the value for user.uid
	 * @mbg.generated  Fri Jan 20 10:10:53 CST 2017
	 */
	public void setUid(Integer uid) {
		this.uid = uid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.direct_url
	 * @return  the value of user.direct_url
	 * @mbg.generated  Fri Jan 20 10:10:53 CST 2017
	 */
	public String getDirectUrl() {
		return directUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.direct_url
	 * @param directUrl  the value for user.direct_url
	 * @mbg.generated  Fri Jan 20 10:10:53 CST 2017
	 */
	public void setDirectUrl(String directUrl) {
		this.directUrl = directUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.direct_pwd
	 * @return  the value of user.direct_pwd
	 * @mbg.generated  Fri Jan 20 10:10:53 CST 2017
	 */
	public String getDirectPwd() {
		return directPwd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.direct_pwd
	 * @param directPwd  the value for user.direct_pwd
	 * @mbg.generated  Fri Jan 20 10:10:53 CST 2017
	 */
	public void setDirectPwd(String directPwd) {
		this.directPwd = directPwd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.name
	 * @return  the value of user.name
	 * @mbg.generated  Fri Jan 20 10:10:53 CST 2017
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.name
	 * @param name  the value for user.name
	 * @mbg.generated  Fri Jan 20 10:10:53 CST 2017
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.sumary
	 * @return  the value of user.sumary
	 * @mbg.generated  Fri Jan 20 10:10:53 CST 2017
	 */
	public String getSumary() {
		return sumary;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.sumary
	 * @param sumary  the value for user.sumary
	 * @mbg.generated  Fri Jan 20 10:10:53 CST 2017
	 */
	public void setSumary(String sumary) {
		this.sumary = sumary;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.title
	 * @return  the value of user.title
	 * @mbg.generated  Fri Jan 20 10:10:53 CST 2017
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.title
	 * @param title  the value for user.title
	 * @mbg.generated  Fri Jan 20 10:10:53 CST 2017
	 */
	public void setTitle(String title) {
		this.title = title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.pice
	 * @return  the value of user.pice
	 * @mbg.generated  Fri Jan 20 10:10:53 CST 2017
	 */
	public Integer getPice() {
		return pice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.pice
	 * @param pice  the value for user.pice
	 * @mbg.generated  Fri Jan 20 10:10:53 CST 2017
	 */
	public void setPice(Integer pice) {
		this.pice = pice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.type
	 * @return  the value of user.type
	 * @mbg.generated  Fri Jan 20 10:10:53 CST 2017
	 */
	public Integer getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.type
	 * @param type  the value for user.type
	 * @mbg.generated  Fri Jan 20 10:10:53 CST 2017
	 */
	public void setType(Integer type) {
		this.type = type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.status
	 * @return  the value of user.status
	 * @mbg.generated  Fri Jan 20 10:10:53 CST 2017
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.status
	 * @param status  the value for user.status
	 * @mbg.generated  Fri Jan 20 10:10:53 CST 2017
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.update_time
	 * @return  the value of user.update_time
	 * @mbg.generated  Fri Jan 20 10:10:53 CST 2017
	 */
	public Integer getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.update_time
	 * @param updateTime  the value for user.update_time
	 * @mbg.generated  Fri Jan 20 10:10:53 CST 2017
	 */
	public void setUpdateTime(Integer updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.create_time
	 * @return  the value of user.create_time
	 * @mbg.generated  Fri Jan 20 10:10:53 CST 2017
	 */
	public Integer getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.create_time
	 * @param createTime  the value for user.create_time
	 * @mbg.generated  Fri Jan 20 10:10:53 CST 2017
	 */
	public void setCreateTime(Integer createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.open_id
	 * @return  the value of user.open_id
	 * @mbg.generated  Fri Jan 20 10:10:53 CST 2017
	 */
	public String getOpenId() {
		return openId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.open_id
	 * @param openId  the value for user.open_id
	 * @mbg.generated  Fri Jan 20 10:10:53 CST 2017
	 */
	public void setOpenId(String openId) {
		this.openId = openId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.subscribe
	 * @return  the value of user.subscribe
	 * @mbg.generated  Fri Jan 20 10:10:53 CST 2017
	 */
	public Integer getSubscribe() {
		return subscribe;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.subscribe
	 * @param subscribe  the value for user.subscribe
	 * @mbg.generated  Fri Jan 20 10:10:53 CST 2017
	 */
	public void setSubscribe(Integer subscribe) {
		this.subscribe = subscribe;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.head_image_url
	 * @return  the value of user.head_image_url
	 * @mbg.generated  Fri Jan 20 10:10:53 CST 2017
	 */
	public String getHeadImageUrl() {
		return headImageUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.head_image_url
	 * @param headImageUrl  the value for user.head_image_url
	 * @mbg.generated  Fri Jan 20 10:10:53 CST 2017
	 */
	public void setHeadImageUrl(String headImageUrl) {
		this.headImageUrl = headImageUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.nickname
	 * @return  the value of user.nickname
	 * @mbg.generated  Fri Jan 20 10:10:53 CST 2017
	 */
	public String getNickname() {
		return nickname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.nickname
	 * @param nickname  the value for user.nickname
	 * @mbg.generated  Fri Jan 20 10:10:53 CST 2017
	 */
	public void setNickname(String nickname) {
		this.nickname = nickname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.sex
	 * @return  the value of user.sex
	 * @mbg.generated  Fri Jan 20 10:10:53 CST 2017
	 */
	public Integer getSex() {
		return sex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.sex
	 * @param sex  the value for user.sex
	 * @mbg.generated  Fri Jan 20 10:10:53 CST 2017
	 */
	public void setSex(Integer sex) {
		this.sex = sex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.unionid
	 * @return  the value of user.unionid
	 * @mbg.generated  Fri Jan 20 10:10:53 CST 2017
	 */
	public String getUnionid() {
		return unionid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.unionid
	 * @param unionid  the value for user.unionid
	 * @mbg.generated  Fri Jan 20 10:10:53 CST 2017
	 */
	public void setUnionid(String unionid) {
		this.unionid = unionid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.email
	 * @return  the value of user.email
	 * @mbg.generated  Fri Jan 20 10:10:53 CST 2017
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.email
	 * @param email  the value for user.email
	 * @mbg.generated  Fri Jan 20 10:10:53 CST 2017
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.mobile
	 * @return  the value of user.mobile
	 * @mbg.generated  Fri Jan 20 10:10:53 CST 2017
	 */
	public String getMobile() {
		return mobile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.mobile
	 * @param mobile  the value for user.mobile
	 * @mbg.generated  Fri Jan 20 10:10:53 CST 2017
	 */
	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.remarks
	 * @return  the value of user.remarks
	 * @mbg.generated  Fri Jan 20 10:10:53 CST 2017
	 */
	public String getRemarks() {
		return remarks;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.remarks
	 * @param remarks  the value for user.remarks
	 * @mbg.generated  Fri Jan 20 10:10:53 CST 2017
	 */
	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}
}